// Jumbolino: a party dice game for a babyshower. Each of the 6 die faces
// is a category; rolling it draws a random prompt from that category for
// the group to act on. There's no scoring — it's just for fun.
export const FACES = [
  {
    id: 'herinnering',
    emoji: '🍼',
    label: 'Herinnering',
    prompts: [
      'Vertel een leuke jeugdherinnering.',
      'Wat was jouw meest onhandige moment als kind?',
      'Deel een dierbare herinnering met de aanstaande ouders.',
      'Vertel over de eerste keer dat je een baby vasthield.',
      'Wat is je grappigste oppas-verhaal?',
      'Vertel een herinnering aan je eigen ouders.',
      'Wat was jouw lievelingsspeelgoed als kind?',
      'Deel een grappige familie-anekdote.',
    ],
  },
  {
    id: 'advies',
    emoji: '👶',
    label: 'Advies',
    prompts: [
      'Geef de aanstaande ouders één gouden opvoedtip.',
      'Wat is het beste advies dat jij ooit kreeg?',
      'Welke fout zou jij afraden om te maken?',
      'Geef tips om goed te slapen met een baby in huis.',
      'Wat zou jij zeker wél doen als ouder?',
      'Geef advies over de eerste nacht thuis met de baby.',
      'Wat is jouw tip voor als de baby huilt?',
      'Welk boek of welke app raad je aan?',
    ],
  },
  {
    id: 'raden',
    emoji: '👣',
    label: 'Raden',
    prompts: [
      'Raad hoeveel de baby gaat wegen.',
      'Raad hoeveel centimeter de baby wordt.',
      'Raad op welke datum de baby geboren wordt.',
      'Raad hoeveel haar de baby heeft bij de geboorte.',
      'Raad hoe laat de baby geboren wordt.',
      'Raad wie de baby het meest gaat lijken.',
      'Raad hoeveel luiers er de eerste week nodig zijn.',
      'Raad welk sterrenbeeld de baby krijgt.',
    ],
  },
  {
    id: 'doen',
    emoji: '🎀',
    label: 'Doen',
    prompts: [
      'Doe een imitatie van een huilende baby.',
      'Zing een slaapliedje.',
      'Doe alsof je een luier verschoont, zonder je handen te gebruiken.',
      'Wieg een denkbeeldige baby in slaap.',
      'Doe een dansje voor de baby.',
      'Vertel een verhaaltje voor het slapengaan.',
      'Doe alsof je een flesje geeft aan een baby.',
      'Maak het geluid na van een baby die blij is.',
    ],
  },
  {
    id: 'naam',
    emoji: '🍭',
    label: 'Naam',
    prompts: [
      'Noem een naam die je mooi vindt voor de baby.',
      'Bedenk een grappige bijnaam voor de baby.',
      'Welke naam zou je zeker afraden?',
      'Noem jouw eigen naam en vertel wat die betekent.',
      'Verzin een superheldennaam voor de baby.',
      'Noem een naam uit je favoriete film of boek.',
      'Bedenk een naam die begint met dezelfde letter als jouw naam.',
      'Welke naam past goed bij de achternaam van de baby?',
    ],
  },
  {
    id: 'wens',
    emoji: '🌙',
    label: 'Wens',
    prompts: [
      'Doe een wens voor de baby.',
      'Wat wens je de aanstaande ouders toe?',
      'Zeg iets liefs tegen de mama-to-be.',
      'Zeg iets liefs tegen de papa-to-be, als die er is.',
      'Wat hoop je dat de baby later wordt?',
      'Deel een wijze levensles voor de baby.',
      'Wat wens je de baby toe voor het eerste levensjaar?',
      'Maak een toost op de nieuwe wereldburger.',
    ],
  },
];
